# Generated by Django 5.2.17 on 2026-09-24 19:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "pending_technician_assignment",
                                "Pending Technician Assignment",
                            ),
                            (
                                "pending_technician_assessment",
                                "Pending Technician Assessment",
                            ),
                            ("pending_poc_review", "Pending Department POC Review"),
                            (
                                "pending_blockage_resolution",
                                "Pending Blockage Resolution",
                            ),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="pending_technician_assignment",
                        max_length=40,
                    ),
                ),
                (
                    "assessment_outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fully_resolved", "Fully Resolved"),
                            ("partially_resolved", "Partially Resolved"),
                            (
                                "needs_reassignment",
                                "Department/Worker Change Suggested",
                            ),
                        ],
                        max_length=30,
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client_office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="organizations.clientoffice",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="closed_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="organizations.department",
                    ),
                ),
                (
                    "department_poc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="poc_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facility_manager_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "floors",
                    models.ManyToManyField(
                        blank=True, related_name="tickets", to="organizations.floor"
                    ),
                ),
                (
                    "issue_types",
                    models.ManyToManyField(
                        help_text="Issue tags.",
                        related_name="tickets",
                        to="organizations.issuetype",
                    ),
                ),
                (
                    "primary_issue_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_tickets",
                        to="organizations.issuetype",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="technician_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TicketComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body_html", models.TextField(blank=True)),
                ("body_text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ticket_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="TicketActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("created", "created the ticket"),
                            ("auto_assigned", "auto-assigned the ticket"),
                            ("assigned_technician", "assigned technician"),
                            ("changed_department", "changed department"),
                            ("changed_status", "changed status of the ticket"),
                            ("resolved", "marked the ticket resolved"),
                            ("closed", "closed the ticket"),
                            ("commented", "commented"),
                        ],
                        max_length=30,
                    ),
                ),
                ("from_value", models.CharField(blank=True, max_length=200)),
                ("to_value", models.CharField(blank=True, max_length=200)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ticket_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="tickets.ticket",
                    ),
                ),
                (
                    "comment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activity",
                        to="tickets.ticketcomment",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("storage_key", models.CharField(max_length=500, unique=True)),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("size", models.PositiveBigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending upload"),
                            ("attached", "Attached"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="tickets.ticket",
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="tickets.ticketcomment",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["status", "-created_at"], name="ticket_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["department", "status"], name="ticket_dept_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["technician", "status"], name="ticket_tech_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["facility_manager", "status"], name="ticket_fm_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "pending_technician_assignment",
                            "pending_technician_assessment",
                            "pending_poc_review",
                            "pending_blockage_resolution",
                            "resolved",
                            "closed",
                        ],
                    )
                ),
                name="ticket_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status", "pending_technician_assessment"), _negated=True
                    ),
                    ("technician__isnull", False),
                    _connector="OR",
                ),
                name="ticket_assessment_requires_technician",
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status__in", ["closed", "resolved"]),
                        ("closed_at__isnull", False),
                    ),
                    models.Q(
                        models.Q(("status__in", ["closed", "resolved"]), _negated=True),
                        ("closed_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="ticket_closed_at_matches_status",
            ),
        ),
        migrations.AddIndex(
            model_name="ticketcomment",
            index=models.Index(
                fields=["ticket", "created_at"], name="comment_ticket_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketactivity",
            index=models.Index(
                fields=["ticket", "created_at"], name="activity_ticket_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ticketactivity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "kind__in",
                        [
                            "created",
                            "auto_assigned",
                            "assigned_technician",
                            "changed_department",
                            "changed_status",
                            "resolved",
                            "closed",
                            "commented",
                        ],
                    )
                ),
                name="activity_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="ticketactivity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "commented"), _negated=True),
                    ("comment__isnull", False),
                    _connector="OR",
                ),
                name="activity_commented_has_comment",
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["status", "created_at"], name="attachment_status_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="attachment",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["pending", "attached"])),
                name="attachment_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="attachment",
            constraint=models.CheckConstraint(
                condition=models.Q(("size__gt", 0)), name="attachment_size_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="attachment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "attached"), _negated=True),
                    ("comment__isnull", False),
                    _connector="OR",
                ),
                name="attachment_attached_has_comment",
            ),
        ),
    ]
