# Generated by Django 5.2.17 on 2026-09-24 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticketactivity',
            name='activity_kind_valid',
        ),
        migrations.AlterField(
            model_name='ticketactivity',
            name='kind',
            field=models.CharField(choices=[('created', 'created the ticket'), ('auto_assigned', 'auto-assigned the ticket'), ('assigned_technician', 'assigned technician'), ('changed_department', 'changed department'), ('changed_status', 'changed status of the ticket'), ('resolved', 'marked the ticket resolved'), ('closed', 'closed the ticket'), ('commented', 'commented'), ('edited_description', 'edited the description')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='ticketactivity',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['created', 'auto_assigned', 'assigned_technician', 'changed_department', 'changed_status', 'resolved', 'closed', 'commented', 'edited_description'])), name='activity_kind_valid'),
        ),
    ]
