# Generated by Django 5.2.17 on 2026-09-24 21:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('tickets', '0002_remove_ticketactivity_activity_kind_valid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='ticket_status_valid',
        ),
        migrations.RemoveConstraint(
            model_name='ticketactivity',
            name='activity_kind_valid',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending_facility_manager_review', 'Pending Facility Manager Review'), ('pending_technician_assignment', 'Pending Technician Assignment'), ('pending_technician_assessment', 'Pending Technician Assessment'), ('pending_poc_review', 'Pending Department POC Review'), ('pending_blockage_resolution', 'Pending Blockage Resolution'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending_facility_manager_review', max_length=40),
        ),
        migrations.AlterField(
            model_name='ticketactivity',
            name='kind',
            field=models.CharField(choices=[('created', 'created the ticket'), ('auto_assigned', 'auto-assigned the ticket'), ('forwarded_to_department', 'forwarded to department'), ('assigned_technician', 'assigned technician'), ('changed_department', 'changed department'), ('changed_status', 'changed status of the ticket'), ('resolved', 'marked the ticket resolved'), ('closed', 'closed the ticket'), ('commented', 'commented'), ('edited_description', 'edited the description')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending_facility_manager_review', 'pending_technician_assignment', 'pending_technician_assessment', 'pending_poc_review', 'pending_blockage_resolution', 'resolved', 'closed'])), name='ticket_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='ticketactivity',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['created', 'auto_assigned', 'forwarded_to_department', 'assigned_technician', 'changed_department', 'changed_status', 'resolved', 'closed', 'commented', 'edited_description'])), name='activity_kind_valid'),
        ),
    ]
