# Generated by Django 5.2.17 on 2026-09-24 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.SlugField(max_length=30, unique=True)),
                (
                    "poc",
                    models.ForeignKey(
                        blank=True,
                        help_text="Point of contact who receives new tickets for this department.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="poc_of_departments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="IssueType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "is_quick",
                    models.BooleanField(
                        default=False, help_text="Shown as a 'Quick Issue' chip."
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issue_types",
                        to="organizations.department",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=80)),
                (
                    "area",
                    models.CharField(
                        help_text="Locality within the city, e.g. 'HSR Layout'.",
                        max_length=80,
                    ),
                ),
            ],
            options={
                "ordering": ["city", "area"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("city", "area"), name="unique_location_area_per_city"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Short code, e.g. 'Harness'.",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="properties",
                        to="organizations.location",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "properties",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ClientOffice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="Unit number within the property, e.g. '1317'.",
                        max_length=30,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offices",
                        to="organizations.client",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offices",
                        to="organizations.property",
                    ),
                ),
            ],
            options={
                "ordering": ["client__name", "property__code", "unit"],
            },
        ),
        migrations.CreateModel(
            name="Floor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.SmallIntegerField()),
                (
                    "label",
                    models.CharField(
                        help_text="Display label, e.g. '2F'.", max_length=20
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="floors",
                        to="organizations.clientoffice",
                    ),
                ),
            ],
            options={
                "ordering": ["office", "level"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("office", "level"), name="unique_floor_level_per_office"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="clientoffice",
            constraint=models.UniqueConstraint(
                fields=("property", "unit"), name="unique_office_unit_per_property"
            ),
        ),
    ]
